import { AfterViewInit, Component, ElementRef, OnDestroy, effect, inject, input } from '@angular/core';
import { Router } from '@angular/router';

export interface LegacyView {
  html: string;
  after?: (root: HTMLElement) => void;
}

/**
 * Hosts HTML produced by the unchanged report renderer (src/legacy/hb-report.js).
 * The markup is generated by our own code with every value escaped, so it is
 * written straight into the host. Links into the app are routed in-app.
 */
@Component({
  selector: 'hb-legacy-view',
  standalone: true,
  template: '',
  host: { class: 'hb-legacy d-block' }
})
export class LegacyViewComponent implements AfterViewInit, OnDestroy {
  readonly view = input<LegacyView | null>(null);
  private el = inject(ElementRef<HTMLElement>);
  private router = inject(Router);
  private ready = false;

  private onClick = (e: MouseEvent) => {
    const a = (e.target as HTMLElement)?.closest?.('a[href]') as HTMLAnchorElement | null;
    if (!a || a.target === '_blank' || e.ctrlKey || e.metaKey) return;
    const href = a.getAttribute('href') || '';
    if (href.startsWith('/')) { e.preventDefault(); this.router.navigateByUrl(href); }
  };

  constructor() {
    effect(() => {
      const v = this.view();
      if (this.ready) this.paint(v);
    });
  }

  ngAfterViewInit(): void {
    this.ready = true;
    this.el.nativeElement.addEventListener('click', this.onClick);
    this.paint(this.view());
  }

  ngOnDestroy(): void {
    this.el.nativeElement.removeEventListener('click', this.onClick);
  }

  private paint(v: LegacyView | null): void {
    const host = this.el.nativeElement as HTMLElement;
    host.innerHTML = v?.html || '';
    if (v?.after) setTimeout(() => v.after!(host), 0);
  }
}
